### ISSUE TITLE
关于 blog 里面的 第一篇文章 Event Loop 调用栈 (call stack)代码片段 出现错误

### ISSUE THREAD

**Issue by Smecta** [zxuqian/zxuqian.cn#8]
## 描述一下问题？
在该文章里介绍的调用栈 (call stack)代码片段 第一行 显示输出结果 // 1, 2, 3 的错误输出问题
**图片展示**
![image](https://user-images.githubusercontent.com/30615458/100497617-984df280-3197-11eb-90e6-6ff1f084cc45.png)

**Comment by zxuqian** [comment]
已改正，感谢指正！
